### ISSUE TITLE
Add Boundary tool re-opens previous boundary

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#25]
The add boundary tool opens up the existing boundary rather than creating a new block.

**Comment by robjtede** [comment]
As in, the add boundary tool should union new paths with the existing pond?

**Comment by guruthree** [comment]
Ideally the boundary tool would start a new shape, but force the first point to be within existing boundary/vegetation areas. Clicking this button at the very least should not _undo_ the last placed vertex, as it currently does.
