### ISSUE TITLE
Boundaries can be moved to exclude vegetation

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#26]
![screenshot at 2017-07-03 14-55-03](https://user-images.githubusercontent.com/3973507/27795867-a9f48b2e-5fff-11e7-8aa4-8411b5aa0558.png)

**Comment by robjtede** [comment]
Related to/duplicate of #20

**Comment by guruthree** [comment]
It's back.

![screenshot at 2017-07-06 10-05-37](https://user-images.githubusercontent.com/3973507/27903889-cf875cd8-6232-11e7-8d90-76c9180520f9.png)
