### ISSUE TITLE
Areas can be subtracted in non-convex shapes

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#27]
![screenshot at 2017-07-03 14-56-33](https://user-images.githubusercontent.com/3973507/27795914-e96d7d24-5fff-11e7-857d-a5a2f6d20164.png)

**Comment by robjtede** [comment]
Whilst this is unexpected behaviour, is it not okay to keep?

**Comment by guruthree** [comment]
I would not allow this. It's inconsistent with how boundaries work, and the triangular point of intersection could cause problems numerically when trying to solve for a flow field in this geometry.
