### ISSUE TITLE
Non-convex vegetation is possible

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#29]
![screenshot at 2017-07-03 14-59-27](https://user-images.githubusercontent.com/3973507/27796014-5026662a-6000-11e7-85d9-21c42b2ef16e.png)

**Comment by robjtede** [comment]
Similarly to #27, is this behaviour not okay to keep?

**Comment by guruthree** [comment]
Same comment as before, it's inconsistent. The numerical implications here are better though than the non-convex subtraction.
