### ISSUE TITLE
Clicking (outlet) button puts geometry outside of design box

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#30]
![screenshot at 2017-07-03 15-03-12](https://user-images.githubusercontent.com/3973507/27796139-d76f3210-6000-11e7-8f76-bd3c3a1013bb.png)

**Comment by guruthree** [comment]
also happens with the inlet button, but not any of the other tool buttons

**Comment by guruthree** [comment]
also lets you put vegetation outside boundary
![screenshot at 2017-07-03 15-04-56](https://user-images.githubusercontent.com/3973507/27796190-07903d2c-6001-11e7-9098-2e122f285d5d.png)

**Comment by robjtede** [comment]
I was not able to replicate this. Closing.

Re-open if it occurs again.
