### ISSUE TITLE
> to show active tool button causes button reflow

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#40]
![b4](https://user-images.githubusercontent.com/3973507/27903498-780336cc-6231-11e7-9e69-6d700e8971b0.png)
![aft4](https://user-images.githubusercontent.com/3973507/27903499-780ad1f2-6231-11e7-80a1-d1a7b38e367e.png)

**Comment by robjtede** [comment]
Yeah I agree its not ideal.
