### ISSUE TITLE
Pressing hot key for tool again does not exit out of tool

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#43]
(Would expect the same behaviour as escape.)

**Comment by robjtede** [comment]
Really? I can't think of a design program that has this behaviour on hotkeys.

**Comment by guruthree** [comment]
Fair point. It just felt like something I wanted at that instant, but thinking back I see how it could be inconsistent. Ignore.

**Comment by mike-brown** [comment]
How do you feel about double-clicking in a place or right-clicking cancelling the drawing instead? That's how I've just tried to exit the drawing, and that is a more standard approach (especially the double-click) -- thoughts?

**Comment by robjtede** [comment]
From what I recall that's more of a CAD style of drawing?

I'm open to implementing it since it's relatively easy but it's certainly not a priority since Escape is fairly intuitive.

**Comment by robjtede** [comment]
I will accept a PR @mike-brown ;)
