### ISSUE TITLE
Need to calculate properties of plants

### ISSUE THREAD

**Issue by EndoMatrix** [mike-brown/ponds-online#53]
Currently, several plant properties are defined based on data obtain from Table 1 in _CFD Modelling of Residence Times in Vegetated Stormwater Ponds_ (Sonnenwald et. al.). Since these values are interdependent, it should not be possible for the user to overdefine the properties of a plant; such that an invalid combination of values may be produced.

Ideally, the user may be able to define a **phi** value, and subsequent properties should be calculated from that where possible.

**Comment by guruthree** [comment]
For aquatic vegetation, phi could conceivably be in the range of 0.005 to 0.35, and d in the range of 0.002 to 0.02. Everything else is a combination of these two.

**Comment by EndoMatrix** [comment]
The calculations have been adjusted so that they depend on **phi** and **diameter** only; and the remaining properties are defined based on these values.
