### ISSUE TITLE
Reset button affecting multiple windows?

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#57]
Step 1: Press reset in Firefox Ponds Online window
Step 2: Hit cancel
Step 3: Have to hit cancel in Chromium Ponds Online window

This seems like a pretty big issue?

Seems like activating tools in one browser will also activate them in the other.

**Comment by guruthree** [comment]
Run Simulation button also starts in both browsers.

**Comment by robjtede** [comment]
IT'S A FEATURE NOT A BUG! 😉 

BrowserSync is forwarding event listeners to other browsers. Won't be an issue in productions.
